language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester tests -s

services:
  - redis-server
