language: php

php:
  - 7.0
  - 7.1
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

script:
  - vendor/bin/tester tests -s -p php

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

services:
  - redis-server
